name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run linting
        run: |
          uv run ruff check . --no-fix
          uv run ruff format --check .

      - name: Run critical tests
        run: |
          uv run pytest tests/test_mcp_server.py tests/test_mcp_tools.py -v --tb=short

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: quick-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies (with dev)
        run: |
          uv sync --dev

      - name: Run python-semantic-release (publish)
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # python-semantic-release expects PYPI token in environment variable named PYPI_API_TOKEN or configured in pyproject
          uv run semantic-release publish
